dist: precise
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.3
  - 3.4
  - 3.5-dev
  - 3.6-dev
  - pypy2.7-5.8.0
  - pypy3.5-5.8.0
  - 3.7-dev
  - nightly
install:
    - pip install --upgrade nose coveralls coverage
    - if [[ $TRAVIS_PYTHON_VERSION == 'pypy'* ]]; then export TRAVIS_WAIT=45; else export TRAVIS_WAIT=20; fi
script:
    travis_wait "${TRAVIS_WAIT}" nosetests --with-coverage --cover-package=neat -vd
after_success:
    coveralls
